// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI/migrations use the DIRECT (non-pooled) connection; the app runtime
    // (src/lib/db.ts) uses DATABASE_URL (the pooler on serverless).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
